# Generated by Django 4.0.4 on 2022-04-22 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=250)),
                ('first_name', models.CharField(max_length=250)),
                ('middle_name', models.CharField(blank=True, max_length=250, null=True)),
                ('last_name', models.CharField(max_length=250)),
                ('suffix', models.CharField(max_length=250)),
                ('location', models.CharField(max_length=250)),
                ('region', models.CharField(max_length=250)),
                ('province', models.CharField(max_length=250)),
                ('municipality', models.CharField(max_length=250)),
                ('barangay', models.CharField(max_length=250)),
                ('purok', models.CharField(max_length=250)),
                ('sex', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=250, null=True)),
                ('age', models.CharField(max_length=250)),
                ('birthday', models.CharField(max_length=250)),
                ('email', models.CharField(max_length=250)),
                ('contact_number', models.CharField(max_length=250)),
                ('civil_status', models.CharField(max_length=250)),
                ('youth_classification', models.CharField(max_length=250)),
                ('youth_age_group', models.CharField(max_length=250)),
                ('work_status', models.CharField(max_length=250)),
                ('educational_background', models.CharField(max_length=250)),
                ('sk_voter', models.BooleanField()),
                ('national_voter', models.BooleanField()),
                ('slug', models.SlugField(max_length=250)),
            ],
        ),
    ]
