# Generated by Django 4.0.4 on 2022-04-23 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiling', '0003_alter_profile_age_alter_profile_barangay_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='region',
            field=models.CharField(blank=True, default='5', max_length=250, null=True),
        ),
    ]
