# Generated by Django 4.0.4 on 2022-04-23 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiling', '0004_alter_profile_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='barangay',
            field=models.CharField(blank=True, default='Obrero', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='municipality',
            field=models.CharField(blank=True, default='Bulan', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='province',
            field=models.CharField(blank=True, default='Sorsogon', max_length=250, null=True),
        ),
    ]
